version: '3'

services:
  knyaz-learning-db:
    image: postgres:11.0
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: library
      POSTGRES_PASSWORD: library